cc_library(
    name = "vector",
    hdrs = ["vector.h"],
    visibility = ["//data_strctures:__pkg__"],
)

cc_binary(
    name = "tests",
    srcs = ["tests.cc"],
    deps = [
        ":vector",
    ],
)
